@startuml test_name
    autonumber

    actor Брокер
    actor Трейдер
    actor Аналитик
    actor Администратор
    
    participant Система

    activate Брокер
        Брокер -> Система: Запрос на регистрацию

    activate Система
        Система -> Брокер: Ответ на регистрацию

    deactivate Система
    deactivate Брокер

    activate Трейдер
        Трейдер -> Система: Запрос на регистрацию

    activate Система
        Система -> Трейдер: Ответ на регистрацию

    deactivate Система
    deactivate Трейдер

    activate Брокер
        Брокер -> Система: Запрос на авторизацию

    activate Система
        Система -> Брокер: Ответ на авторизацию

    deactivate Система
    deactivate Брокер

    activate Трейдер
        Трейдер -> Система: Запрос на авторизацию

    activate Система
        Система -> Трейдер: Ответ на авторизацию

    deactivate Система
    deactivate Трейдер

    activate Аналитик
        Аналитик -> Система: Запрос на авторизацию

    activate Система
        Система -> Аналитик: Ответ на авторизацию

    deactivate Система
    deactivate Аналитик

    activate Администратор
        Администратор -> Система: Запрос на авторизацию

    activate Система
        Система -> Администратор: Ответ на авторизацию

    deactivate Система
    deactivate Администратор

    activate Брокер
        Брокер -> Система: Запрос на создание топика

    activate Система
        Система -> Брокер: Ответ на создание топика

    deactivate Система
    deactivate Брокер

    activate Трейдер
        Трейдер -> Система: Запрос на создание топика

    activate Система
        Система -> Трейдер: Ответ на создание топика

    deactivate Система
    deactivate Трейдер

    activate Аналитик
        Аналитик -> Система: Запрос на создание топика

    activate Система
        Система -> Аналитик: Ответ на создание топика

    deactivate Система
    deactivate Аналитик

    activate Администратор
        Администратор -> Система: Запрос на создание топика

    activate Система
        Система -> Администратор: Ответ на создание топика

    deactivate Система
    deactivate Администратор

    activate Брокер
        Брокер -> Система: Запрос на создание сообщения

    activate Система
        Система -> Брокер: Ответ на создание сообщения

    deactivate Система
    deactivate Брокер

    activate Трейдер
        Трейдер -> Система: Запрос на создание сообщения

    activate Система
        Система -> Трейдер: Ответ на создание сообщения

    deactivate Система
    deactivate Трейдер

    activate Аналитик
        Аналитик -> Система: Запрос на создание сообщения

    activate Система
        Система -> Аналитик: Ответ на создание сообщения

    deactivate Система
    deactivate Аналитик

    activate Администратор
        Администратор -> Система: Запрос на создание сообщения

    activate Система
        Система -> Администратор: Ответ на создание сообщения

    deactivate Система
    deactivate Администратор

    activate Брокер
        Брокер -> Система: Запрос на удаление сообщения

    activate Система
        Система -> Брокер: Ответ на удаление сообщения

    deactivate Система
    deactivate Брокер

    activate Трейдер
        Трейдер -> Система: Запрос на удаление сообщения

    activate Система
        Система -> Трейдер: Ответ на удаление сообщения

    deactivate Система
    deactivate Трейдер

    activate Аналитик
        Аналитик -> Система: Запрос на удаление сообщения

    activate Система
        Система -> Аналитик: Ответ на удаление сообщения

    deactivate Система
    deactivate Аналитик

    activate Администратор
        Администратор -> Система: Запрос на удаление сообщения

    activate Система
        Система -> Администратор: Ответ на удаление сообщения

    deactivate Система
    deactivate Администратор

    activate Брокер
        Брокер -> Система: Запрос на удаление топика

    activate Система
        Система -> Брокер: Ответ на удаление топика

    deactivate Система
    deactivate Брокер

    activate Трейдер
        Трейдер -> Система: Запрос на удаление топика

    activate Система
        Система -> Трейдер: Ответ на удаление топика

    deactivate Система
    deactivate Трейдер

    activate Аналитик
        Аналитик -> Система: Запрос на удаление топика

    activate Система
        Система -> Аналитик: Ответ на удаление топика

    deactivate Система
    deactivate Аналитик

    activate Администратор
        Администратор -> Система: Запрос на удаление топика

    activate Система
        Система -> Администратор: Ответ на удаление топика

    deactivate Система
    deactivate Администратор

    activate Брокер
        Брокер -> Система: Запрос на привязку банковской карты

    activate Система
        Система -> Брокер: Ответ на привязку банковской карты

    deactivate Брокер
    deactivate Система

    activate Трейдер
        Трейдер -> Система: Запрос на привязку банковской карты

    activate Система
        Система -> Трейдер: Ответ на привязку банковской карты

    deactivate Система
    deactivate Трейдер

    activate Брокер
        Брокер -> Система: Запрос на добавление криптокошелька

    activate Система
        Система -> Брокер: Ответ на добавление криптокошелька

    deactivate Система
    deactivate Брокер

    activate Трейдер
        Трейдер -> Система: Запрос на добавление криптокошелька

    activate Система
        Система -> Трейдер: Ответ на добавление криптокошелька

    deactivate Система
    deactivate Трейдер

    activate Брокер
        Брокер -> Система: Запрос на создание торгового ордера

    activate Система
        Система -> Брокер: Ответ на создание торгового ордера

    deactivate Система
    deactivate Брокер

    activate Трейдер
        Трейдер -> Система: Запрос на создание торгового ордера

    activate Система
        Система -> Трейдер: Ответ на создание торгового ордера

    deactivate Система
    deactivate Трейдер

    activate Брокер
        Брокер -> Система: Запрос на создание торгового ордера

    activate Система
        Система -> Брокер: Ответ на создание торгового ордера

    deactivate Система
    deactivate Брокер

    activate Трейдер
        Трейдер -> Система: Запрос на создание торгового ордера

    activate Система
        Система -> Трейдер: Ответ на создание торгового ордера

    deactivate Система
    deactivate Трейдер
@enduml