@startuml trading_platform
    autonumber

    actor Продавец_ТрейдерБрокер
    actor Покупатель_ТрейдерБрокер

    participant Система

    activate Продавец_ТрейдерБрокер
        Продавец_ТрейдерБрокер -> Система: Запрос на создание ордера

    activate Система
        Система -> Система: Сохранение данных в финансовой и аналитической БД
        Система --> Продавец_ТрейдерБрокер: Ответ на запрос на создание ордера

    deactivate Система
    deactivate Продавец_ТрейдерБрокер

    activate Покупатель_ТрейдерБрокер
        Покупатель_ТрейдерБрокер -> Система: Запрос на исполнение ордера

    activate Система
        Система -> Система: Сохранение данных в финансовой и аналитической БД
        Система --> Покупатель_ТрейдерБрокер: Ответ на исполнение ордера
        Система -> Покупатель_ТрейдерБрокер: Отправка уведомления об исполнении ордера
        Система -> Продавец_ТрейдерБрокер: Отправка уведомления об исполнении ордера

    deactivate Система
    deactivate Покупатель_ТрейдерБрокер

@enduml